.TH "cargos_lib_csi_has_nt" 3 "0.1.3" "cargos\-lib" "cargos\-lib"
.SH NAME
cargos_lib_csi_has_nt
.SH SYNOPSIS
.B #include <cargos.h>
.sp
.BI "int cargos_lib_csi_has_nt(cargos_lib_t * " inst ");"
.SH ARGUMENTS
.IP "cargos_lib_t * inst" 12
 Library instance.
.SH "DESCRIPTION"
Return whether the csi log, also, includes net tracker information.
.SH "RETURN VALUE"
 Returns true if the log contains net tracker information.
.SH "REPORTING BUGS"
Report bugs to <porto_@users.sourceforge.net>.
.SH COPYRIGHT
Copyright \(co 2006 Georgios Portokalidis.
.br
Permission is granted to make and distribute verbatim copies of this
manual provided the copyright notice and this permission notice are
preserved on all copies.
