.TH "cargos_lib_create" 3 "0.1" "cargos\-lib" "cargos\-lib"
.SH NAME
cargos_lib_create
.SH SYNOPSIS
.B #include <cargos.h>
.sp
.BI "cargos_lib_t * cargos_lib_create( " void ");"
.SH ARGUMENTS
.IP " void" 12
.SH "DESCRIPTION"

Create a new library instance.
.SH "RETURN VALUE"
 Returns newly allocated library instance.
.SH "REPORTING BUGS"
Report bugs to <porto_@users.sourceforge.net>.
.SH COPYRIGHT
Copyright \(co 2006 Georgios Portokalidis.
.br
Permission is granted to make and distribute verbatim copies of this
manual provided the copyright notice and this permission notice are
preserved on all copies.
