.TH "cargos_lib_csi_regnidx" 3 "0.1.3" "cargos\-lib" "cargos\-lib"
.SH NAME
cargos_lib_csi_regnidx
.SH SYNOPSIS
.B #include <cargos.h>
.sp
.BI "uint32_t cargos_lib_csi_regnidx(cargos_lib_t * " inst ", cargos_lib_regidx_t " index ");"
.SH ARGUMENTS
.IP "cargos_lib_t * inst" 12
 Library instance.
.IP "cargos_lib_regidx_t index" 12
 The register index.
.SH "DESCRIPTION"
Return the network index of a register in the Argos csi log associated with
the instance. The network index is valid only for csi logs generated using 
a 'net tracker' enabled Argos and tainted registers. It represents the
network index of the value in the network trace (usually net_tracker.log)
that is responsible for tainting the register.
See also \n.B \"cargos_lib_csi_reg()\"\n.
.SH "RETURN VALUE"
 Returns the network index of a register. Unspecified if the
register is not tainted.
.SH "REPORTING BUGS"
Report bugs to <porto_@users.sourceforge.net>.
.SH COPYRIGHT
Copyright \(co 2006 Georgios Portokalidis.
.br
Permission is granted to make and distribute verbatim copies of this
manual provided the copyright notice and this permission notice are
preserved on all copies.
