.TH "cargos_lib_csi_mbnext" 3 "0.1.3" "cargos\-lib" "cargos\-lib"
.SH NAME
cargos_lib_csi_mbnext
.SH SYNOPSIS
.B #include <cargos.h>
.sp
.BI "cargos_lib_mb_t * cargos_lib_csi_mbnext(cargos_lib_t * " inst ");"
.SH ARGUMENTS
.IP "cargos_lib_t * inst" 12
 Library instance.
.SH "DESCRIPTION"
Return the next memory block using the built-in memory block iterator. The
user is not required to call \n.B \"argos_lib_csi_mbfirst()\"\n before using this
function.
.SH "RETURN VALUE"
 Returns the next memory block, or NULL if there are no more
blocks.
.SH "REPORTING BUGS"
Report bugs to <porto_@users.sourceforge.net>.
.SH COPYRIGHT
Copyright \(co 2006 Georgios Portokalidis.
.br
Permission is granted to make and distribute verbatim copies of this
manual provided the copyright notice and this permission notice are
preserved on all copies.
