.TH "cargos_lib_nt_bytes" 3 "0.1.1" "cargos\-lib" "cargos\-lib"
.SH NAME
cargos_lib_nt_bytes
.SH SYNOPSIS
.B #include <cargos.h>
.sp
.BI "uint32_t cargos_lib_nt_bytes(cargos_lib_t * " inst ");"
.SH ARGUMENTS
.IP "cargos_lib_t * inst" 12
 Library instance.
.SH "DESCRIPTION"
Return the number of network data bytes within the net tracker log
associated with a library instance.
.SH "RETURN VALUE"
 Returns the number of network data bytes within the net 
tracker log.
.SH "REPORTING BUGS"
Report bugs to <porto_@users.sourceforge.net>.
.SH COPYRIGHT
Copyright \(co 2006 Georgios Portokalidis.
.br
Permission is granted to make and distribute verbatim copies of this
manual provided the copyright notice and this permission notice are
preserved on all copies.
