.TH "cargos_lib_destroy" 3 "0.1" "cargos\-lib" "cargos\-lib"
.SH NAME
cargos_lib_destroy
.SH SYNOPSIS
.B #include <cargos.h>
.sp
.BI "void cargos_lib_destroy(cargos_lib_t * " lib ");"
.SH ARGUMENTS
.IP "cargos_lib_t * lib" 12
 Library instance.
.SH "DESCRIPTION"
Destroy a library instance.
.SH "REPORTING BUGS"
Report bugs to <porto_@users.sourceforge.net>.
.SH COPYRIGHT
Copyright \(co 2006 Georgios Portokalidis.
.br
Permission is granted to make and distribute verbatim copies of this
manual provided the copyright notice and this permission notice are
preserved on all copies.
